apiVersion: v1
kind: Secret
metadata:
  name: {{ include "excimer.fullname" . }}
  labels:
    {{- include "excimer.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ .Values.database.host | b64enc | quote }}
  DB_PORT: {{ .Values.database.port | toString | b64enc | quote }}
  DB_USER: {{ .Values.database.user | b64enc | quote }}
  DB_PASS: {{ .Values.database.pass | b64enc | quote }}
  DB_NAME: {{ .Values.database.name  | b64enc | quote }}
  APP_KEY: {{ .Values.app.key | b64enc | quote }}
  APP_URL: {{ .Values.app.url | b64enc | quote }}