name: Release Charts

on:
  push:
    branches:
      - master

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  helm:
    environment:
      name: helm chart
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Add Helm repos
        run: |
          helm repo add common https://charts.bitnami.com/bitnami

      - name: Package
        run: helm package helm --destination .helm

      - name: Index
        run: helm repo index .helm

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.helm'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
